### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by bradjones1** [Aryess/matrix-php-sdk#1]
A quick inquiry as to the maintenance status of this package; I am considering a Matrix implementation and appreciate the work done here. I think this is great prior art and would love to coordinate rather than fork. Is this still actively maintained? Looks like a solid group of contributors (including @frankdejonge who I really respect) so not sure if folks have moved on or, what :-)

Thanks for all the work on this, regardless.

**Comment by Aryess** [comment]
Hi @bradjones1, as you can see from the commit history, this hasn't been updated in a while, nor can I remember if I actually did fully port it. 

For the contributors let me clear this right up, the solid list of names on the side is the contributors from the template I used (thephpleague/skeleton), probably should have cleared the `.git` and start from scratch. For the actual Matrix integration, this was just me by myself over a few evenings a while ago, so there isn't that much work.

I am not sure I will have much more time to work on this than I have in the last 2~3 years though so I don't mind either adding you to this repo, or even handing it over.

**Comment by bradjones1** [comment]
Adding me as a maintainer would be great; I maintain a number of modules on drupal.org and hopefully my github record also demonstrates my judgment, and I'd love to give this a little... love as I work on it. Thanks!

**Comment by Aryess** [comment]
Done, welcome on board :)

**Comment by bradjones1** [comment]
@Aryess Thanks... I don't think I see an invite from github to join as a maintainer, though - can you check? Cheers.

**Comment by bradjones1** [comment]
Thanks :-)
