### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by bradjones1** [Aryess/matrix-php-sdk#2]
This package should be added to packagist.org. :-)

**Comment by Aryess** [comment]
Once fully ported and tested, definitely should, yes!

**Comment by bradjones1** [comment]
Added - https://packagist.org/packages/aryess/php-matrix-sdk

**Comment by bradjones1** [comment]
Figure no reason to wait until a full port/release; if folks are installing directly it's worth at least providing through packagist so they'll get notifications of releases.
